version: '3'
services:
  tenpo-postgres:
    image: "postgres"
    env_file:
      - database.env # configure postgres
      volumes:
        - database-data:/var/lib/postgresql/data/
    ports:
    - "5432"
    restart: always

  registration-login:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - tenpo-postgres
